name = "synthetix-perps-market"
version = "<%= package.version %>-testable"
description = "Perps market implementation"

[setting.coreProxyOwner]
description = "owner of v3 core proxy"
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.owner]
description = "perps market owner"
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.synthetixPackage]
defaultValue = "synthetix:<%= package.version %>-testable"
depends = []

[setting.spotMarketPackage]
defaultValue = "synthetix-spot-market:<%= package.version %>-testable"
depends = []

[import.synthetix]
source = "<%= settings.synthetixPackage %>"

[import.spotMarket]
source = "<%= settings.spotMarketPackage %>"

[contract.PerpsMarketFactoryModule]
artifact = "PerpsMarketFactoryModule"

[contract.AsyncOrderModule]
artifact = "AsyncOrderModule"

[contract.AsyncOrderSettlementPythModule]
artifact = "AsyncOrderSettlementPythModule"

[contract.AsyncOrderCancelModule]
artifact = "AsyncOrderCancelModule"

[contract.PerpsAccountModule]
artifact = "PerpsAccountModule"

[contract.PerpsMarketModule]
artifact = "PerpsMarketModule"

[contract.LiquidationModule]
artifact = "LiquidationModule"

[contract.CollateralConfigurationModule]
artifact = "CollateralConfigurationModule"

[contract.MarketConfigurationModule]
artifact = "MarketConfigurationModule"

[contract.FeatureFlagModule]
artifact = "contracts/modules/FeatureFlagModule.sol:FeatureFlagModule"

[contract.CoreModule]
artifact = "contracts/modules/CoreModule.sol:CoreModule"

[contract.InitialProxy]
artifact = "contracts/Proxy.sol:Proxy"
args = ["<%= contracts.CoreModule.address %>", "<%= settings.owner %>"]
abiOf = ["CoreModule"]
salt = "<%= settings.salt %>"

[contract.GlobalPerpsMarketModule]
artifact = "GlobalPerpsMarketModule"

# Core
[router.PerpsMarketRouter]
contracts = [
    "synthetix.AccountModule",
    "synthetix.AssociatedSystemsModule",
    "CoreModule",
    "PerpsMarketFactoryModule",
    "PerpsAccountModule",
    "PerpsMarketModule",
    "AsyncOrderModule",
    "AsyncOrderSettlementPythModule",
    "AsyncOrderCancelModule",
    "FeatureFlagModule",
    "LiquidationModule",
    "MarketConfigurationModule",
    "CollateralConfigurationModule",
    "GlobalPerpsMarketModule",
]

[invoke.upgrade_proxy]
target = ["InitialProxy"]
fromCall.func = "owner"
func = "upgradeTo"
args = ["<%= contracts.PerpsMarketRouter.address %>"]
factory.PerpsMarketProxy.abiOf = ["PerpsMarketRouter"]
factory.PerpsMarketProxy.event = "Upgraded"
factory.PerpsMarketProxy.arg = 0

[invoke.init_account]
target = ["PerpsMarketProxy"]
from = "<%= settings.owner %>"
func = "initOrUpgradeNft"
args = [
    "<%= formatBytes32String('accountNft') %>",
    "Perpetual Futures Account",
    "snxPerpsAcct",
    "",
    "<%= imports.synthetix.contracts.AccountRouter.address %>",
]
depends = ["invoke.upgrade_proxy"]
factory.AccountProxy.abiOf = ["synthetix.AccountRouter"]
factory.AccountProxy.event = "AssociatedSystemSet"
factory.AccountProxy.arg = 2

# add pool owner to feature flag allow list
[invoke.addPerpsMarketToFeatureFlag]
target = ["synthetix.CoreProxy"]
func = "addToFeatureFlagAllowlist"
from = "<%= settings.coreProxyOwner %>"
args = [
    "<%= formatBytes32String('registerMarket') %>",
    "<%= contracts.PerpsMarketProxy.address %>",
]

[invoke.addCreateMarketToFeatureFlag]
target = ["PerpsMarketProxy"]
func = "addToFeatureFlagAllowlist"
from = "<%= settings.owner %>"
args = ["<%= formatBytes32String('createMarket') %>", "<%= settings.owner %>"]

[invoke.addPerpsSystemToFeatureFlag]
target = ["PerpsMarketProxy"]
func = "setFeatureFlagAllowAll"
from = "<%= settings.owner %>"
args = ["<%= formatBytes32String('perpsSystem') %>", true]

# add snxUSD as the only priority to deduct from on a given account, as default
[invoke.setSynthDeductionPriority]
target = ["PerpsMarketProxy"]
func = "setSynthDeductionPriority"
from = "<%= settings.owner %>"
args = [[0]]

[contract.MockPythERC7412Wrapper]
artifact = "contracts/mocks/MockPythERC7412Wrapper.sol:MockPythERC7412Wrapper"

[contract.FeeCollectorMock]
artifact = "contracts/mocks/FeeCollectorMock.sol:FeeCollectorMock"
