name = "owned_fee_collector"
version = "<%= package.version %>"
description = "Colelcts fees on behalf of an owner"

[setting.owner]
defaultValue = "0x0000000000000000000000000000000000000000"

[setting.owner_fee_share]
defaultValue = "500000000000000000"

[setting.fee_token]
defaultValue = "0x0000000000000000000000000000000000000000"

[contract.owned_fee_collector]
artifact = "contracts/OwnedFeeCollector.sol:OwnedFeeCollector"
args = [
    "<%= settings.owner %>",
    "<%= settings.owner_fee_share %>",
    "<%= settings.fee_token %>",
]
create2 = true
