name = "perps-sandbox"
version = "2"
description = "Sandbox environment for development with perps"

[setting.owner]
# Matches owner of core system that's provisions on Cannon network
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266" # PK 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
# We can change the owner of pools and modules deployed in the Sandbox if we want
#defaultValue = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC" # PK 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
description = "Hardhat/Anvil first test account"

#
#
# TODO: We will need to use Pyth Mock, so these settings will change.
#
#
[setting.pyth_price_verification_address]
defaultValue = "0x5955C1478F0dAD753C7E2B4dD1b4bC530C64749f"

[setting.pyth_feed_url]
defaultValue = "https://api.synthetix.io/pyth-testnet/api/get_vaa_ccip?data={data}"

[setting.pyth_eth_feed_id]
defaultValue = "0xca80ba6dc32e08d06f1aa886011eed1d77c77be9eb761cc10d72b7d0a2fd57a6"

#
#
# Provision Synthetix V3 Core sandbox
#
#
[import.core_sandbox]
source = "core-sandbox"

#
#
# Provision mintable Wrapped Ethereum token $WETH
#
#
[provision.weth_token]
source = "mintable-token"
sourcePreset = "permissionless-mint"
options.symbol = "WETH"
options.name = "Wrapped Ethereum"

#
#
# Synth ETH
#
#
[invoke.create_synth_eth]
target = ["core_sandbox.spot_factory.SpotMarketProxy"]
fromCall.func = "owner"
func = "createSynth"
args = ["Synthetic ETH", "sETH", "<%= settings.owner %>"]
extra.synth_eth_market_id.event = "SynthRegistered"
extra.synth_eth_market_id.arg = 0
extra.synth_eth_token_address.event = "SynthRegistered"
extra.synth_eth_token_address.arg = 1

[invoke.register_eth_oracle_node_with_constant_price]
target = ["core_sandbox.synthetix.oracle_manager.Proxy"]
func = "registerNode"
args = [
    8, # 8 = constant
    "<%= defaultAbiCoder.encode(['int256'], [parseEther('1000')]) %>", # 1 parameter: price
    [
    ],
]
extra.eth_oracle_id.event = "NodeRegistered"
extra.eth_oracle_id.arg = 0

[invoke.configure_price_data_for_synth_eth]
target = ["core_sandbox.spot_factory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_eth_market_id %>"]
func = "updatePriceData"
args = [
    "<%= extras.synth_eth_market_id %>",
    "<%= extras.eth_oracle_id %>",
    "<%= extras.eth_oracle_id %>",
]

[invoke.configure_atomic_fixed_fee_for_synth_eth]
target = ["core_sandbox.spot_factory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_eth_market_id %>"]
func = "setAtomicFixedFee"
args = ["<%= extras.synth_eth_market_id %>", "<%= MaxUint256 %>"]

[invoke.configure_settlement_strategy_for_synth_eth]
target = ["core_sandbox.spot_factory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_eth_market_id %>"]
func = "addSettlementStrategy"
args = [
    "<%= extras.synth_eth_market_id %>",
    # strategyType = 1 (pyth)
    { strategyType = "1", settlementDelay = "15", settlementWindowDuration = "60", priceVerificationContract = "<%= settings.pyth_price_verification_address %>", feedId = "<%= settings.pyth_eth_feed_id %>", url = "<%= settings.pyth_feed_url %>", settlementReward = 0, minimumUsdExchangeAmount = "<%= parseEther('0.000001') %>", maxRoundingLoss = "<%= parseEther('0.000001') %>", priceDeviationTolerance = "<%= parseEther('1') %>", disabled = false },
]

[invoke.configure_async_fixed_fee_for_synth_eth]
target = ["core_sandbox.spot_factory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_eth_market_id %>"]
func = "setAsyncFixedFee"
args = ["<%= extras.synth_eth_market_id %>", "<%= parseEther('0.001') %>"]

[invoke.configure_maximum_market_collateral_for_synth_eth]
target = ["core_sandbox.synthetix.CoreProxy"]
fromCall.func = "owner"
func = "configureMaximumMarketCollateral"
args = [
    "<%= extras.synth_eth_market_id %>",
    "<%= imports.weth_token.contracts.MintableToken.address %>",
    "<%= MaxUint256 %>",
]

[invoke.initialise_synth_weth_wrapper_with_unlimited_cap]
target = ["core_sandbox.spot_factory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_eth_market_id %>"]
func = "setWrapper"
args = [
    "<%= extras.synth_eth_market_id %>",
    "<%= imports.weth_token.contracts.MintableToken.address %>",
    "<%= MaxUint256 %>",
]

[invoke.configure_market_skew_scale_for_synth_eth]
target = ["core_sandbox.spot_factory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_eth_market_id %>"]
func = "setMarketSkewScale"
args = ["<%= extras.synth_eth_market_id %>", "<%= parseEther('100000') %>"]

[invoke.configure_wrapper_fees_for_synth_eth]
target = ["core_sandbox.spot_factory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_eth_market_id %>"]
func = "setWrapperFees"
args = [
    "<%= extras.synth_eth_market_id %>",
    "<%= parseEther('0.0001') %>",
    "<%= parseEther('0.0001') %>",
]

#
#
# Provision Perps factory
#
#
[provision.perps_factory]
source = "synthetix-perps-market:dev"
depends = ["import.core_sandbox"]

[invoke.permit_owner_to_register_markets]
target = ["core_sandbox.synthetix.CoreProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = ["<%= formatBytes32String('registerMarket') %>", "<%= settings.owner %>"]

#
#
# Perps ETH
#
#
[invoke.create_eth_perps_market]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["100", "Ethereum", "ETH"]
extra.perps_eth_market_id.event = "MarketCreated"
extra.perps_eth_market_id.arg = 0
depends = ['invoke.permit_owner_to_register_markets']

[invoke.configure_price_data_for_perps_eth]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= extras.perps_eth_market_id %>", # uint128 perpsMarketId
    "<%= extras.eth_oracle_id %>",
    # bytes32 feedId
]

[invoke.configure_settlement_strategy_for_perps_eth]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [
    "<%= extras.perps_eth_market_id %>",
    # strategyType = 0 (pyth)
    { strategyType = "0", settlementDelay = "15", settlementWindowDuration = "60", priceWindowDuration = "600", priceVerificationContract = "<%= settings.pyth_price_verification_address %>", feedId = "<%= settings.pyth_eth_feed_id %>", url = "<%= settings.pyth_feed_url %>", settlementReward = 0, priceDeviationTolerance = "<%= parseEther('1') %>", disabled = false },
]

[invoke.configure_funding_parameters_for_perps_eth]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= extras.perps_eth_market_id %>", # uint128 marketId
    "<%= parseEther('1000000') %>",      # uint256 skewScale
    "<%= parseEther('9') %>",
    # uint256 maxFundingVelocity
]

[invoke.configure_order_fees_for_perps_eth]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= extras.perps_eth_market_id %>", # uint128 marketId
    "<%= parseEther('0.0002') %>",       # uint256 makerFeeRatio
    "<%= parseEther('0.0005') %>",
    # uint256 takerFeeRatio
]

[invoke.configure_max_market_size_for_perps_eth]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = [
    "<%= extras.perps_eth_market_id %>", # uint128 marketId
    "<%= parseEther('100000') %>",
    # uint256 maxMarketSize
]

[invoke.configure_max_liquidation_parameters_for_perps_eth]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= extras.perps_eth_market_id %>",          # uint128 marketId
    "<%= parseEther('1') %>",                     # uint256 maxLiquidationLimitAccumulationMultiplier
    "30",                                         # uint256 maxSecondsInLiquidationWindow
    "<%= parseEther('0.0016') %>",                # uint256 maxLiquidationPd
    "0x0000000000000000000000000000000000000000",
    # address endorsedLiquidator
]

[invoke.configure_liquidation_parameters_for_perps_eth]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= extras.perps_eth_market_id %>", # uint128 marketId
    "<%= parseEther('1') %>",            # uint256 initialMarginRatioD18
    "<%= parseEther('0.02') %>",         # uint256 minimumInitialMarginRatioD18
    "<%= parseEther('0.5') %>",          # uint256 maintenanceMarginScalarD18
    "<%= parseEther('0.01') %>",         # uint256 flagRewardRatioD18
    "<%= parseEther('0') %>",
    # uint256 minimumPositionMargin
]

[invoke.configure_locked_oi_ratio_for_perps_eth]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = [
    "<%= extras.perps_eth_market_id %>", # uint128 marketId
    "<%= parseEther('0.5') %>",
    # uint256 lockedOiRatioD18
]

[invoke.configure_max_collateral_amount_for_perps_eth]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxCollateralAmount"
args = [
    "<%= extras.synth_eth_market_id %>", # uint128 synthMarketId
    "<%= MaxUint256 %>",
    # uint256 collateralAmount
]

#
#
# Global Perps configuration
#
#
[invoke.configure_perps_liquidation_reward_limits]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationRewardGuards"
args = ["<%= parseEther('1') %>", "<%= parseEther('500') %>"]

[invoke.configure_perps_max_collateral_for_susd]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxCollateralAmount"
args = ["0", "<%= MaxUint256 %>"]

[invoke.configure_perps_synth_deduction_priority]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSynthDeductionPriority"
args = [
    [
        "<%= imports.core_sandbox.extras.synth_box_market_id %>",
        "<%= extras.synth_eth_market_id %>",
        #        "<%= extras.synth_btc_market_id %>",
        "0",
    ],
]

[invoke.configure_per_account_caps_perps]
target = ["perps_factory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setPerAccountCaps"
args = ["5", "3"]

#
#
#
# Create Spartan Council pool
#
#
[invoke.configure_spartan_council_pool]
target = ["core_sandbox.synthetix.CoreProxy"]
fromCall.func = "getPoolOwner"
fromCall.args = ["<%= imports.core_sandbox.extras.spartan_council_pool_id %>"]
func = "setPoolConfiguration"
args = [
    "<%= imports.core_sandbox.extras.spartan_council_pool_id %>",
    [
        { marketId = "<%= imports.core_sandbox.extras.synth_box_market_id %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
        { marketId = "<%= extras.synth_eth_market_id %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
        { marketId = "<%= imports.perps_factory.extras.superMarketId %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
    ],
]
