name: Contract sizes

on: [push]

jobs:
  size:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [core-contracts, core-modules, synthetix-main]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run build
      - name: Compile contracts
        run: npm run --workspace=./packages/${{ matrix.package }} compile-contracts
      - name: Execute size command
        run: npm run --workspace=./packages/${{ matrix.package }} size-contracts
