name: Contract sizes

on: [push]

jobs:
  size:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [core-contracts, core-modules, synthetix-main]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.8.0"
          cache: "npm"
      - run: npm ci
      - name: Compile contracts
        run: npm run --workspace=./packages/${{ matrix.package }} compile-contracts
      - name: Execute size command
        run: npm run --workspace=./packages/${{ matrix.package }} size-contracts
