name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [
            core-contracts,
            core-utils,
            core-modules,
            hardhat-router,
            sample-project,
            main,
          ]
        include:
          - package: core-contracts
            workspace: "@synthetixio/core-contracts"
            coverage-file: utils/core-contracts/coverage.json
            size-contracts: true
          - package: core-utils
            workspace: "@synthetixio/core-utils"
            coverage-file: utils/core-utils/coverage/lcov.info
          - package: core-modules
            workspace: "@synthetixio/core-modules"
            coverage-file: utils/core-modules/coverage.json
            size-contracts: true
          - package: hardhat-router
            workspace: "@synthetixio/hardhat-router"
            coverage-file: utils/hardhat-router/coverage/lcov.info
          - package: main
            workspace: "@synthetixio/main"
            size-contracts: true
    steps:
      - name: Install Foundry (Cannon)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: anvil -V
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Execute tests
        run: REPORT_GAS=true npm run --workspace=${{ matrix.workspace }} coverage
      - if: ${{ matrix.coverage-file }}
        name: Upload ${{ matrix.workspace }} coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ${{ matrix.coverage-file }}
          flags: ${{ matrix.package }}
      - if: ${{ matrix.size-contracts }}
        name: Execute size command
        run: npm run --workspace=${{ matrix.workspace }} size-contracts
