name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.8.0"
          cache: "npm"
      - run: npm ci
      - name: Execute tests
        run: npm run coverage
      - name: Upload core-contracts coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: packages/core-contracts/coverage.json
          flags: core-contracts
      - name: Upload core-js coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: packages/core-js/coverage/lcov.info
          flags: core-js
      - name: Upload core-modules coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: packages/core-modules/coverage.json
          flags: core-modules
      - name: Upload deployer coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: packages/deployer/coverage/lcov.info
          flags: deployer
      - name: Upload synthetix-main coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: packages/synthetix-main/coverage.json
          flags: synthetix-main

  test-sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.8.0"
          cache: "npm"
      - run: npm ci
      - name: Execute tests
        run: npm test
