name: Test

on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CANNON_IPFS_URL: "http://127.0.0.1:5001"
      CANNON_PUBLISH_IPFS_URL: "http://127.0.0.1:5001"
    strategy:
      fail-fast: false
      matrix:
        workspace: [
            "@synthetixio/main",
            "@synthetixio/oracle-manager",
            # "@synthetixio/governance", # no tests :/

            "@synthetixio/core-contracts",
            "@synthetixio/core-utils",
            "@synthetixio/core-modules",
            "@synthetixio/hardhat-storage",
            "@synthetixio/sample-project",

            # "@synthetixio/legacy-market", # tests fail
            "@synthetixio/spot-market",
            "@synthetixio/perps-market",

            "@synthetixio/core-subgraph",
            "@synthetixio/spot-market-subgraph",
            "@synthetixio/perps-market-subgraph",
          ]

    steps:
      - name: Install Foundry (Cannon)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: anvil -V
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
          cache: "yarn"
      - uses: ibnesayeed/setup-ipfs@92d412e0dad36c06ffab50733e9c624896a0964f
        with:
          run_daemon: true

      - run: yarn install --immutable --immutable-cache
      - run: yarn workspaces foreach --topological-dev --recursive --verbose --from "${{ matrix.workspace }}" run build:ts
      - run: yarn workspaces foreach --topological-dev --recursive --verbose --from "${{ matrix.workspace }}" run build-testable

      - name: Execute size-contracts command
        run: |
          if yarn workspace ${{ matrix.workspace }} run | grep size-contracts; then
            yarn workspace ${{ matrix.workspace }} run size-contracts
          else
            echo 'SKIP. No "size-contracts" script'
          fi

      - name: Check storage.dump.sol is up-to-date
        run: |
          if yarn workspace ${{ matrix.workspace }} run | grep check:storage; then
            yarn workspace ${{ matrix.workspace }} run check:storage
          else
            echo 'SKIP. No "check:storage" script'
          fi

      - name: Execute tests
        run: |
          if yarn workspace ${{ matrix.workspace }} run | grep test; then
            REPORT_GAS=true yarn workspace ${{ matrix.workspace }} run test
          else
            echo 'SKIP. No "test" script'
          fi
